#!/usr/bin/ruby

require "fileutils"

def run(cmd)
  puts cmd
  if !system(cmd)
    STDERR.puts "Command failed. Exiting."
    exit 1
  end
end

def build_image(name)
  run("docker build -t #{name} #{name}")
end

def build_api_image(image_name, server_name)
  run("openssl req -x509 -newkey rsa:2048 -keyout #{image_name}/server.key -out #{image_name}/server.crt -days 1000 -nodes -subj '/CN=#{server_name}'")

  FileUtils.copy("#{image_name}/server.crt", "client/certificates/#{image_name}.crt")

  run("docker build -t #{image_name} #{image_name}")
end


build_image("server")

build_api_image("rubygems", "rubygems.org")
build_api_image("api.rubygems", "api.rubygems.org")
build_api_image("obs", "api.opensuse.org")

build_image("client")


puts "Success."
