#!/usr/bin/ruby

require "fileutils"

def run(cmd)
  puts cmd
  if !system(cmd)
    STDERR.puts "Command failed. Exiting."
    exit 1
  end
end

run("docker build -t server server")

run("openssl req -x509 -newkey rsa:2048 -keyout rubygems/server.key -out rubygems/server.crt -days 1000 -nodes -subj '/CN=api.rubygems.org'")

run("docker build -t rubygems rubygems")

FileUtils.copy("rubygems/server.crt", "client/certificates/rubygems.crt")
run("docker build -t client client")

puts "Success."
